services:
#  nest-api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: nest-api
#    networks:
#      - nest-app
#    restart: always
#    ports:
#      - 3000:3000
#    depends_on:
#      - postgres
#    env_file:
#      - .env

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=xnqbU9dKjJQRp8eKB41Q
      - POSTGRES_DB=artlist
    networks:
      - nest-app
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-prisma-docker-db
networks:
  nest-app:
    name: nest-app