import type { Metadata } from "next";
import "./globals.css";
import { type ReactNode } from "react";
import { Toaster } from "@/components/ui-library/toaster";
import { Providers } from "@/components/Providers";
import { Footer } from "@/components/Footer";
import { Navigation } from "@/components/navigation/Navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = Readonly<{
  children: ReactNode;
}>;

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="pl">
      <body>
        <Providers>
          <Navigation />

          {children}

          <Footer />

          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
